# Generated by Django 4.1.6 on 2023-02-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incluir', '0002_alter_entrada_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['data']},
        ),
    ]
